export const TRYING_TO_UNLINK_SITE = 'TRYING_TO_UNLINK_SITE';
export const PORTAL_SITE_OPEN_CONFIRM_UNLINK = 'PORTAL_SITE_OPEN_CONFIRM_UNLINK';
export const PORTAL_SITE_CLOSE_CONFIRM_UNLINK = 'PORTAL_SITE_CLOSE_CONFIRM_UNLINK';