---
kind: pipeline
type: kubernetes
name: pr

trigger:
  event:
  - pull_request
  - push
  branch:
  - walt/*

steps:
  # https://discourse.drone.io/t/how-to-exit-a-pipeline-early-without-failing/3951
  # If a change is entirely documentation, skip the expensive build & test steps.
  - name: short circuit docs changes
    image: docker:git
    commands:
    -  ./build.assets/drone/diff-is-all-docs.sh $DRONE_COMMIT_BEFORE..$DRONE_COMMIT_AFTER && exit 78 || exit 0
  - name: fetch tags
    image: docker:git
    commands:
      - git fetch --tags
  - name: wait for docker
    image: docker
    commands:
      - timeout 15s /bin/sh -c 'while [ ! -S /var/run/docker.sock ]; do sleep 1; done'
      - docker version
    volumes:
      - name: dockersock
        path: /var/run
  - name: build
    image: docker:git
    environment:
      GITHUB_RO_KEY_PR:
        from_secret: GITHUB_RO_KEY_PR
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_S3_RO_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_S3_RO_SECRET_ACCESS_KEY
    commands:
      - apk add --no-cache make bash libc6-compat aws-cli
      - mkdir -m 0700 /root/.ssh && echo "$GITHUB_RO_KEY_PR" > /root/.ssh/id_ed25519 && chmod 600 /root/.ssh/id_ed25519
      - ssh-keyscan -H github.com > /root/.ssh/known_hosts 2>/dev/null && chmod 600 /root/.ssh/known_hosts
      - make -C e production telekube opscenter
    volumes:
      - name: dockersock
        path: /var/run
  - name: unit test
    image: docker:git
    commands:
      - apk add --no-cache make bash libc6-compat
      - make -C e test
      - make test
    volumes:
      - name: dockersock
        path: /var/run
  - name: build robotest images
    image: docker:git
    commands:
      - apk add --no-cache make bash libc6-compat
      - make -C e/assets/robotest images
    volumes:
      - name: dockersock
        path: /var/run
  - name: run robotest
    image: docker:git
    environment:
      GCP_ROBOTEST_CREDENTIALS:
        from_secret: GCP_ROBOTEST_CREDENTIALS
      # These files need to be in a volume that the docker service has access to
      # We choose /tmp to accommodate https://github.com/gravitational/robotest/blob/3774f8641439b19c4e0e598db8f87c52ea0e4817/docker/suite/run_suite.sh#L106
      SSH_KEY: /tmp/secrets/robotest
      SSH_PUB: /tmp/secrets/robotest.pub
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/secrets/gcp.json
    commands:
      - apk add --no-cache make bash
      - mkdir -p $(dirname $SSH_KEY)
      - ssh-keygen -t ed25519 -N '' -f $SSH_KEY
      - echo "$GCP_ROBOTEST_CREDENTIALS" > $GOOGLE_APPLICATION_CREDENTIALS
      - make -C e robotest-run
    volumes:
      - name: dockersock
        path: /var/run
      - name: dockertmp
        path: /tmp

services:
  - name: run docker daemon
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run
      - name: dockertmp
        path: /tmp

volumes:
  - name: dockersock
    temp: {}
  - name: dockertmp
    temp: {}

---
kind: pipeline
type: kubernetes
name: docs-pr

trigger:
  event:
  - pull_request

steps:
  - name: wait for docker
    image: docker
    commands:
      - timeout 15s /bin/sh -c 'while [ ! -S /var/run/docker.sock ]; do sleep 1; done'
      - docker version
    volumes:
      - name: dockersock
        path: /var/run
  - name: build buildbox
    image: docker:git
    commands:
      - apk add --no-cache make
      - make -C docs bbox
    volumes:
      - name: dockersock
        path: /var/run
  - name: build
    image: docker:git
    commands:
      - apk add --no-cache make
      - make -C docs docs
    volumes:
      - name: dockersock
        path: /var/run
  - name: lint
    image: docker:git
    commands:
      - apk add --no-cache make
      - make -C docs lint
    volumes:
      - name: dockersock
        path: /var/run

services:
  - name: run docker daemon
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: dockersock
    temp: {}
---
kind: signature
hmac: e9323499f782e3399a10b08f74541617bf96545b2fe19a69ca972fb8fe933c9e

...
