/*
Copyright 2018 Gravitational, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

export const TRYING_TO_LOGIN = 'TRYING_TO_LOGIN';
export const TRYING_TO_COMPLETE_SIGNUP = 'TRYING_TO_COMPLETE_SIGNUP';
export const TRYING_TO_INVITE = 'TRYING_TO_INVITE';
export const TRYING_TO_RESET_USER = 'TRYING_TO_RESET_USER';
export const TRYING_TO_INIT_APP = 'TRYING_TO_INIT_APP';
export const TRYING_TO_INIT_SITE_K8S = 'TRYING_TO_INIT_SITE_K8S';
export const FETCHING_USER_TOKEN = 'FETCHING_USER_TOKEN';
export const FETCHING_SITES = 'FETCHING_SITES';
export const TRYING_TO_UNLINK_SITE = 'TRYING_TO_UNLINK_SITE';
export const TRYING_TO_DELETE_SITE = 'TRYING_TO_DELETE_SITE';
export const TRYING_TO_CHANGE_PSW = 'TRYING_TO_CHANGE_PSW';
export const TRYING_TO_UPDATE_USER = 'TRYING_TO_UPDATE_USER';
export const TRYING_TO_DELETE_USER = 'TRYING_TO_DELETE_USER';
export const TRYING_TO_DELETE_INVITE = 'TRYING_TO_DELETE_INVITE';
export const TRYING_TO_VALIDATE_DOMAIN_NAME = 'TRYING_TO_VALIDATE_DOMAIN_NAME';
export const TRYING_TO_CREATE_NEW_SITE = 'TRYING_TO_CREATE_NEW_SITE';
export const TRYING_TO_START_INSTALL = 'TRYING_TO_START_INSTALL';
export const TRYING_TO_START_APP_UPD_OPERATION = 'TRYING_TO_START_APP_UPD_OPERATION';
export const TRYING_TO_CREATE_EXPAND_OPERATION = 'TRYING_TO_CREATE_EXPAND_OPERATION';
export const TRYING_TO_START_EXPAND_OPERATION = 'TRYING_TO_START_EXPAND_OPERATION';
export const TRYING_TO_DELETE_EXPAND_OPERATION = 'TRYING_TO_DELETE_EXPAND_OPERATION';
export const TRYING_TO_INIT_PORTAL = 'TRYING_TO_INIT_PORTAL';
export const TRYING_TO_INIT_INSTALLER = 'TRYING_TO_INIT_INSTALLER';
export const TRYING_TO_DELETE_APP = 'TRYING_TO_DELETE_APP';
export const TRYING_TO_UPDATE_SITE_CONFIG_MAP = 'TRYING_TO_UPDATE_SITE_CONFIG_MAP';
export const TRYING_TO_UPDATE_SITE_LICENSE = 'TRYING_TO_UPDATE_SITE_LICENSE';
export const TRYING_TO_UPDATE_LOG_FORWARDER = 'TRYING_TO_UPDATE_LOG_FORWARDER';
export const TRYING_TO_VALIDATE_LICENSE = 'TRYING_TO_VALIDATE_LICENSE';
export const TRYING_TO_UPDATE_SITE_REMOTE_ACCESS = 'TRYING_TO_UPDATE_SITE_REMOTE_ACCESS';
export const TRYING_TO_CREATE_INSTALL_LINK = 'TRYING_TO_CREATE_INSTALL_LINK';
export const TRYING_TO_START_SHRINK_OPERATION = 'TRYING_TO_START_SHRINK_OPERATION';
export const TRYING_TO_UPDATE_RETENTION_VALUES = 'TRYING_TO_UPDATE_RETENTION_VALUES';
export const TRYING_TO_DELETE_ROLE = 'TRYING_TO_DELETE_ROLE';
export const TRYING_TO_DELETE_AUTH_PROVIDER = 'TRYING_TO_DELETE_AUTH_PROVIDER';
export const TRYING_SAVE_TLS_CERT = 'TRYING_SAVE_TLS_CERT';
export const TRYING_TO_INIT_UNINSTALLER = 'TRYING_TO_INIT_UNINSTALLER';
export const TRYING_TO_DELETE_RESOURCE = 'TRYING_TO_DELETE_RESOURCE';
export const TRYING_TO_SAVE_RESOURCE = 'TRYING_TO_SAVE_RESOURCE';
export const TRYING_TO_COMPLETE_USER_TOKEN = 'TRYING_TO_COMPLETE_USER_TOKEN';