export const TRYING_TO_DELETE_APP = 'TRYING_TO_DELETE_APP';
export const TRYING_TO_CREATE_INSTALL_LINK = 'TRYING_TO_CREATE_INSTALL_LINK';
export const PORTAL_APPS_OPEN_CONFIRM_DELETE = 'PORTAL_APPS_OPEN_CONFIRM_DELETE';
export const PORTAL_APPS_CLOSE_CONFIRM_DELETE = 'PORTAL_APPS_CLOSE_CONFIRM_DELETE';

