apiVersion: bundle.gravitational.io/v2
kind: SystemApplication
metadata:
  name: dns-app
  resourceVersion: "0.0.0"
  namespace: kube-system
hooks:
  install:
    job: |
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: dns-app-install
      spec:
        template:
          metadata:
            name: dns-app-install
          spec:
            restartPolicy: OnFailure
            containers:
            - name: hook
              image: quay.io/gravitational/debian-tall:0.0.1
              command: ["/usr/local/bin/kubectl", "apply", "-f", "/var/lib/gravity/resources/dns.yaml"]
  update:
      job: |
        apiVersion: batch/v1
        kind: Job
        metadata:
          name: dns-app-update
        spec:
          template:
            metadata:
              name: dns-app-update
            spec:
              restartPolicy: OnFailure
              containers:
              - name: hooks
                image: dns-app-hooks:0.0.1
                args: ["update"]
  rollback:
      job: |
        apiVersion: batch/v1
        kind: Job
        metadata:
          name: dns-app-rollback
        spec:
          template:
            metadata:
              name: dns-app-rollback
            spec:
              restartPolicy: OnFailure
              containers:
              - name: hooks
                image: dns-app-hooks:0.0.1
                args: ["rollback"]
