@startuml
skinparam BackgroundColor #white
skinparam RoundCorner 20
skinparam note {
  BackgroundColor #yellow
}
skinparam sequence {
	ArrowColor DeepSkyBlue
	ActorBorderColor DeepSkyBlue
	LifeLineBorderColor blue
	LifeLineBackgroundColor #A9DCDF

	ParticipantBorderColor DeepSkyBlue
	ParticipantBackgroundColor DodgerBlue
	ParticipantFontName Consolas
	ParticipantFontSize 17
	ParticipantFontColor #A9DCDF

	ActorBackgroundColor aqua
	ActorFontColor DeepSkyBlue
	ActorFontSize 17
	ActorFontName Aapex
}

actor user
participant process as P
box systemd unit
participant driver as DP
participant "peer" as PP
participant "agent" as A
participant "register agent" as RA
end box
participant "Ops Center" as W
participant "installer agent" as IA
database "state database" as db order 100

title Installing from Ops Center (joining agent)

user -> P : start from agent URL
activate P
P -> P : prerequisites
note left
  # ensure no local state
  # validate configuration
  # execute local preflight checks
  # pick advertise IP
end note

== Initialization ==

P -> DP : start (if not yet running)
activate DP
DP -> RA : register agent and start register loop
activate RA
RA -> W : <<register agent>>
RA <- W : <<register agent response>>
note right
join the installer agent chosen
by the Ops Center
end note

== Execute Operation ==

user -> W : create cluster
user -> W : create/start operation

loop until operation has been created
RA -> W : <<register agent>>
RA -> W : fetch operation
end loop
deactivate RA

DP -> db : create/read state\nfrom /usr/local/share/gravity/join
DP -> PP : init
activate PP
note right
  # reset logins
  # log into peer
  # setup state directory
end note

DP -> PP : start
PP -> A : start
activate A
A -> IA : connect
A -> A : prerequisites
note right
  # init service user/export binary
  # validate server profile
end note

loop until operation has completed
P -> db : poll progress
end loop

A <- IA : accept remote commands
return done

return shut down agent
return exit wait
return done

@enduml
