@startuml
skinparam BackgroundColor #white
skinparam RoundCorner 20
skinparam note {
  BackgroundColor #yellow
}
skinparam sequence {
	ArrowColor DeepSkyBlue
	ActorBorderColor DeepSkyBlue
	LifeLineBorderColor blue
	LifeLineBackgroundColor #A9DCDF

	ParticipantBorderColor DeepSkyBlue
	ParticipantBackgroundColor DodgerBlue
	ParticipantFontName Consolas
	ParticipantFontSize 17
	ParticipantFontColor #A9DCDF

	ActorBackgroundColor aqua
	ActorFontColor DeepSkyBlue
	ActorFontSize 17
	ActorFontName Aapex
}

actor user
database "state database" as db order 100

title Installing from command line

create "process" as P
user -> P : start
activate P
P -> P : ensure no local state
note left #yellow
this verifies
that the node does not have
any cluster state
end note

P -> P : validate configuration

== Initialization ==

P -> db : create state\nin /tmp/gravity-wizard

create "wizard process" as W
P -> W : init
activate W
note right: start internal processes

create "process" as I
P -> I : init
activate I
I -> I : validate configuration
I -> W : log into wizard
note right: connect to wizard's API endpoint
I -> I : bootstrap
note right
  # (CLI) export binary / set up state directory
  # export RPC creds
end note
I -> I : generate install token
P -> I : start
I -> W : create cluster
W -> I : create cluster response
I -> I : execute local preflight checks
I -> W : create install operation
I <- W : create install operation response

== Execute Operation ==

create "agent" as A
I -> A : start
activate A
A -> A : wait for other agents
A -> A : start operation
loop
A -> db : poll progress
end loop
P -> I : wait
return shut down agent
return exit wait
return done
return done

@enduml
