@startuml
skinparam BackgroundColor #EEEBDC
skinparam RoundCorner 20
skinparam note {
  BackgroundColor #yellow
}
skinparam sequence {
	ArrowColor DeepSkyBlue
	ActorBorderColor DeepSkyBlue
	LifeLineBorderColor blue
	LifeLineBackgroundColor #A9DCDF

	ParticipantBorderColor DeepSkyBlue
	ParticipantBackgroundColor DodgerBlue
	ParticipantFontName Consolas
	ParticipantFontSize 17
	ParticipantFontColor #A9DCDF

	ActorBackgroundColor aqua
	ActorFontColor DeepSkyBlue
	ActorFontSize 17
	ActorFontName Aapex
}

actor user
participant "wizard process" as W order 30
participant "cluster operator" as C order 40
database "state database" as db order 100


title Joining a node (existing cluster or installation)

create "process" as P
user -> P : start
activate P
P -> P : ensure no local state
note left #yellow
this verifies
that the node does not have
any cluster state
end note

P -> P : validate configuration

== Initialization ==

P -> db : create state\nin /usr/local/share/gravity/join

create "peer" as PP
P -> PP : init
activate PP
PP -> PP : bootstrap
note right
  # reset logins
  # log into peer
  # setup state directory
end note

P -> PP : start
create "install agent" as A
PP-> A : start
activate A
A -> W : connect
note right : if this is an installation
A -> C : connect
note right : if this is joining\na node in existing cluster
A -> A : prerequisites
note right
  # init service user/export binary
  # validate server profile
end note

== Execute Operation ==

alt if installing
A <-> W : accept remote commands
else if expanding
A -> C : wait for operation
A <- A : wait for other agents
A -> C : create operation plan
db <-> C : sync operation plan

A -> A : execute plan
end
return done

P -> PP : wait

return done
return done

@enduml
