apiVersion: batch/v1
kind: Job
metadata:
  name: nodes-deprovision
  namespace: default
spec:
  activeDeadlineSeconds: 240
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: nodes-deprovision
        image: quay.io/gravitational/provisioner:ci.82
        imagePullPolicy: Always
        args: ['nodes-deprovision']
        volumeMounts:
        - mountPath: /mnt/state
          name: state-volume
      volumes:
      - name: state-volume
        emptyDir: {}
